[project]
name = "gestion-risques"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "openpyxl>=3.1.5",
    "pytest>=9.0.2",
    "scipy>=1.17.0",
    "streamlit>=1.53.1",
    "yfinance>=1.1.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
